/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luisb' at '26/10/16 14:31' with Gradle 3.1
 *
 * @author luisb, @date 26/10/16 14:31
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
